# Title
title: "Panagiotis Rigas"
# Logo
logo: "/assets/images/logo.png"
# Theme
theme: jekyll-theme-minimal
# Show
show_downloads: false
# include navbar
{% include navbar.html %} # path is relative to the _includes folder